# Generated by Django 4.2.21 on 2025-05-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armsApp', '0006_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airlines',
            options={'verbose_name_plural': 'Airlines'},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={},
        ),
        migrations.AlterField(
            model_name='airlines',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='airport',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Confirmed'), ('2', 'Cancelled')], default='0', max_length=2),
        ),
    ]
